### ISSUE TITLE
微信小程序开发记录

### ISSUE THREAD

**Issue by zhaobinglong** [zhaobinglong/myBlog#88]
## 参考
https://juejin.cn/post/6913802456900042766

**Comment by zhaobinglong** [comment]
## 代码格式自动纠错

## 参考
https://developers.weixin.qq.com/community/develop/doc/000020aa8ecaa8ba77262808456800

**Comment by zhaobinglong** [comment]
## API Promise化

**Comment by zhaobinglong** [comment]
## 请求库封装

**Comment by zhaobinglong** [comment]
## 调用服务端接口生成小程序二维码
![image](https://user-images.githubusercontent.com/8922614/104832159-0f675380-58ca-11eb-8208-bd0b0ff31245.png)

## 坑1
scene的参数值必须有，没有就报格式不符合要求

## express收到二进制后直接返回image给前端
```javascript
request({
			url: path,
			method: "POST",
			encoding: null,
			body: JSON.stringify(req.body)	
		}, function(error, response, body) {
			// 这里收到的是二进制buffer，需要把二进制转为图片返回给前端
			res.set({
				'Content-Type': 'image/png',
			})
			res.send(body)
}); 
```

**Comment by zhaobinglong** [comment]
## 加载自定义字体
```
const util = require('utils/util.js');
 
App({
    
  onLaunch: function () {
    //加载思源黑体
    util.getFontFamily();
  },
})
 
//这个方法建议放到公共文件中，例如我这里是utils.js
function getFontFamily() {
  wx.loadFontFace({
    family: 'webfont',
    source: 'url("//d.sicq.org/assets/src/SourceHanSansCN-Normal.ttf")',//这个文件放到您的服务器根目录下
    success: function (res) {
      console.log(res.status) // loaded 
    },
    fail: function (res) {
      console.log(res.status) // error 
    },
    complete: function (res) {
      console.log(res.status);
    }
  });

```

## 参考
https://blog.csdn.net/u011280778/article/details/90476364

**Comment by zhaobinglong** [comment]
## 解密用户手机号码报错
```json
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>Illegal Buffer</h1><h2></h2><pre>Error: Illegal Buffer
    at WXBizDataCrypt.decryptData (/Users/zhaobinglong/Desktop/github/nurse-helper/api/public/javascripts/WXBizDataCrypt.js:25:11)
    at /Users/zhaobinglong/Desktop/github/nurse-helper/api/routes/wechat.js:68:17
    at Layer.handle [as handle_request] (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/layer.js:95:5)
    at next (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/layer.js:95:5)
    at /Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/index.js:281:22
    at param (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/index.js:354:14)
    at param (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/index.js:365:14)
    at Function.process_params (/Users/zhaobinglong/Desktop/github/nurse-helper/api/node_modules/_express@4.16.4@express/lib/router/index.js:410:3)</pre></body></html>
```

## 坑1: session_key必须有效

## 使用云开发直接获取加密数据
由于该错误一直无法解决，更改为使用云开发方案替代
